### ISSUE TITLE
Pinout Korrekt?

### ISSUE THREAD

**Issue by HartmutA** [timo1235/ocs2.x-esp32-panel-software#1]
Hallo Timo,
kann es sein, dass das Pinmapping nicht mit dem Platinenlayout 1.04 übereinstimmt?
Dort steht:
#define JOYSTICK_X_PIN 32
#define JOYSTICK_Y_PIN 33
#define JOYSTICK_Z_PIN 36
Aber nach dem Layout würde ich denken, dass es 36, 39 und 34 ist. Oder habe ich Tomaten auf den Augen ;-)?
![grafik](https://user-images.githubusercontent.com/62034753/204394438-6919fa53-98d7-4c4d-96ea-23d5d7d9a4c1.png)

**Comment by taltholtmann** [comment]
Oh ja. Das stimmt. Es hat sich ein wenig bei der letzten Version geändert. Passe ich heute Abend an.

**Comment by timo1235** [comment]
Ich habe das pinout angepasst. Leider ist dabei noch ein kleiner Fehler mit dem Menü Button aufgefallen. 
Daher ist erstmal der Button4 der Menü-Button. Ich werde das mit der nächsten PCB Version beheben.
